import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Header from "@/ppdhome/components/header";
import Footer from "@/ppdhome/components/footer";
import Background from "./components/background";
import BWWrapper from "./components/BWWrapper"; // 👈 เพิ่มตัวนี้
import { IBM_Plex_Sans_Thai } from "next/font/google";

export const dynamic = "force-dynamic";

const ibmThai = IBM_Plex_Sans_Thai({
  subsets: ["thai"],
  weight: ["300", "400", "500"],
  variable: "--font-thai",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${ibmThai.variable} antialiased`}>

        {/* 👇 ย้าย logic ไป component */}
        <BWWrapper />

        <Background />
        <Header />
        <main className="pt-34">
          {children}
        </main>

        <Footer />

      </body>
    </html>
  );
}