import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Header from "@/ppdhome/components/header";
import Footer from "@/ppdhome/components/footer";
import Background from "./components/background";
import { getPool } from "@lib/db";
export const dynamic = "force-dynamic";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// 👇 ต้องเป็น async
export default async function RootLayout({ children }) {

  const pool = await getPool();
  const result = await pool
    .request()
    .query("SELECT bwMode FROM SiteSettings WHERE id = 1");

  const bwMode = result.recordset[0].bwMode;

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {bwMode && (
          <div className="fixed inset-0 pointer-events-none bg-black/70 mix-blend-saturation z-[9998]" />
        )}

        <Background />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
