services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "PpdHome@1234"
      MSSQL_MEMORY_LIMIT_MB: 384
    volumes:
      - mssql_data:/var/opt/mssql
    ports:
      - "1434:1433"

  web:
    build: .
    restart: always
    depends_on:
      - sqlserver
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      DB_HOST: sqlserver
      DB_USER: sa
      DB_PASSWORD: PpdHome@1234
    env_file:
      - .env.local
    command: npm run dev

volumes:
  mssql_data: